/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSolicitudesRouteImport } from './routes/_app/solicitudes'
import { Route as AppMisTareasRouteImport } from './routes/_app/mis-tareas'
import { Route as AppCuentaRouteImport } from './routes/_app/cuenta'
import { Route as AppCentroDeAsignacionesRouteImport } from './routes/_app/centro-de-asignaciones'
import { Route as AppAjustesRouteImport } from './routes/_app/ajustes'
import { Route as AppTareasRouteRouteImport } from './routes/_app/tareas/route'
import { Route as AppUsuariosIndexRouteImport } from './routes/_app/usuarios/index'
import { Route as AppTablerosIndexRouteImport } from './routes/_app/tableros/index'
import { Route as AppUsuariosUserSlugRouteImport } from './routes/_app/usuarios/$userSlug'
import { Route as AppTablerosTableroRouteImport } from './routes/_app/tableros/$tablero'
import { Route as AppTareasNuevaIndexRouteImport } from './routes/_app/tareas/nueva/index'
import { Route as AppTareasNuevaImpresaRouteImport } from './routes/_app/tareas/nueva/impresa'
import { Route as AppTareasNuevaEspecialRouteImport } from './routes/_app/tareas/nueva/especial'
import { Route as AppTareasNuevaEcommerceRouteImport } from './routes/_app/tareas/nueva/ecommerce'
import { Route as AppTareasNuevaDigitalRouteImport } from './routes/_app/tareas/nueva/digital'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSolicitudesRoute = AppSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMisTareasRoute = AppMisTareasRouteImport.update({
  id: '/mis-tareas',
  path: '/mis-tareas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCuentaRoute = AppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCentroDeAsignacionesRoute = AppCentroDeAsignacionesRouteImport.update({
  id: '/centro-de-asignaciones',
  path: '/centro-de-asignaciones',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTareasRouteRoute = AppTareasRouteRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTablerosIndexRoute = AppTablerosIndexRouteImport.update({
  id: '/tableros/',
  path: '/tableros/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsuariosUserSlugRoute = AppUsuariosUserSlugRouteImport.update({
  id: '/usuarios/$userSlug',
  path: '/usuarios/$userSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTablerosTableroRoute = AppTablerosTableroRouteImport.update({
  id: '/tableros/$tablero',
  path: '/tableros/$tablero',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTareasNuevaIndexRoute = AppTareasNuevaIndexRouteImport.update({
  id: '/nueva/',
  path: '/nueva/',
  getParentRoute: () => AppTareasRouteRoute,
} as any)
const AppTareasNuevaImpresaRoute = AppTareasNuevaImpresaRouteImport.update({
  id: '/nueva/impresa',
  path: '/nueva/impresa',
  getParentRoute: () => AppTareasRouteRoute,
} as any)
const AppTareasNuevaEspecialRoute = AppTareasNuevaEspecialRouteImport.update({
  id: '/nueva/especial',
  path: '/nueva/especial',
  getParentRoute: () => AppTareasRouteRoute,
} as any)
const AppTareasNuevaEcommerceRoute = AppTareasNuevaEcommerceRouteImport.update({
  id: '/nueva/ecommerce',
  path: '/nueva/ecommerce',
  getParentRoute: () => AppTareasRouteRoute,
} as any)
const AppTareasNuevaDigitalRoute = AppTareasNuevaDigitalRouteImport.update({
  id: '/nueva/digital',
  path: '/nueva/digital',
  getParentRoute: () => AppTareasRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/tareas': typeof AppTareasRouteRouteWithChildren
  '/ajustes': typeof AppAjustesRoute
  '/centro-de-asignaciones': typeof AppCentroDeAsignacionesRoute
  '/cuenta': typeof AppCuentaRoute
  '/mis-tareas': typeof AppMisTareasRoute
  '/solicitudes': typeof AppSolicitudesRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/tableros/$tablero': typeof AppTablerosTableroRoute
  '/usuarios/$userSlug': typeof AppUsuariosUserSlugRoute
  '/tableros': typeof AppTablerosIndexRoute
  '/usuarios': typeof AppUsuariosIndexRoute
  '/tareas/nueva/digital': typeof AppTareasNuevaDigitalRoute
  '/tareas/nueva/ecommerce': typeof AppTareasNuevaEcommerceRoute
  '/tareas/nueva/especial': typeof AppTareasNuevaEspecialRoute
  '/tareas/nueva/impresa': typeof AppTareasNuevaImpresaRoute
  '/tareas/nueva': typeof AppTareasNuevaIndexRoute
}
export interface FileRoutesByTo {
  '/tareas': typeof AppTareasRouteRouteWithChildren
  '/ajustes': typeof AppAjustesRoute
  '/centro-de-asignaciones': typeof AppCentroDeAsignacionesRoute
  '/cuenta': typeof AppCuentaRoute
  '/mis-tareas': typeof AppMisTareasRoute
  '/solicitudes': typeof AppSolicitudesRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/tableros/$tablero': typeof AppTablerosTableroRoute
  '/usuarios/$userSlug': typeof AppUsuariosUserSlugRoute
  '/tableros': typeof AppTablerosIndexRoute
  '/usuarios': typeof AppUsuariosIndexRoute
  '/tareas/nueva/digital': typeof AppTareasNuevaDigitalRoute
  '/tareas/nueva/ecommerce': typeof AppTareasNuevaEcommerceRoute
  '/tareas/nueva/especial': typeof AppTareasNuevaEspecialRoute
  '/tareas/nueva/impresa': typeof AppTareasNuevaImpresaRoute
  '/tareas/nueva': typeof AppTareasNuevaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/tareas': typeof AppTareasRouteRouteWithChildren
  '/_app/ajustes': typeof AppAjustesRoute
  '/_app/centro-de-asignaciones': typeof AppCentroDeAsignacionesRoute
  '/_app/cuenta': typeof AppCuentaRoute
  '/_app/mis-tareas': typeof AppMisTareasRoute
  '/_app/solicitudes': typeof AppSolicitudesRoute
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/tableros/$tablero': typeof AppTablerosTableroRoute
  '/_app/usuarios/$userSlug': typeof AppUsuariosUserSlugRoute
  '/_app/tableros/': typeof AppTablerosIndexRoute
  '/_app/usuarios/': typeof AppUsuariosIndexRoute
  '/_app/tareas/nueva/digital': typeof AppTareasNuevaDigitalRoute
  '/_app/tareas/nueva/ecommerce': typeof AppTareasNuevaEcommerceRoute
  '/_app/tareas/nueva/especial': typeof AppTareasNuevaEspecialRoute
  '/_app/tareas/nueva/impresa': typeof AppTareasNuevaImpresaRoute
  '/_app/tareas/nueva/': typeof AppTareasNuevaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/tareas'
    | '/ajustes'
    | '/centro-de-asignaciones'
    | '/cuenta'
    | '/mis-tareas'
    | '/solicitudes'
    | '/'
    | '/auth'
    | '/tableros/$tablero'
    | '/usuarios/$userSlug'
    | '/tableros'
    | '/usuarios'
    | '/tareas/nueva/digital'
    | '/tareas/nueva/ecommerce'
    | '/tareas/nueva/especial'
    | '/tareas/nueva/impresa'
    | '/tareas/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tareas'
    | '/ajustes'
    | '/centro-de-asignaciones'
    | '/cuenta'
    | '/mis-tareas'
    | '/solicitudes'
    | '/'
    | '/auth'
    | '/tableros/$tablero'
    | '/usuarios/$userSlug'
    | '/tableros'
    | '/usuarios'
    | '/tareas/nueva/digital'
    | '/tareas/nueva/ecommerce'
    | '/tareas/nueva/especial'
    | '/tareas/nueva/impresa'
    | '/tareas/nueva'
  id:
    | '__root__'
    | '/_app'
    | '/_app/tareas'
    | '/_app/ajustes'
    | '/_app/centro-de-asignaciones'
    | '/_app/cuenta'
    | '/_app/mis-tareas'
    | '/_app/solicitudes'
    | '/_app/'
    | '/auth/'
    | '/_app/tableros/$tablero'
    | '/_app/usuarios/$userSlug'
    | '/_app/tableros/'
    | '/_app/usuarios/'
    | '/_app/tareas/nueva/digital'
    | '/_app/tareas/nueva/ecommerce'
    | '/_app/tareas/nueva/especial'
    | '/_app/tareas/nueva/impresa'
    | '/_app/tareas/nueva/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/solicitudes': {
      id: '/_app/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof AppSolicitudesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mis-tareas': {
      id: '/_app/mis-tareas'
      path: '/mis-tareas'
      fullPath: '/mis-tareas'
      preLoaderRoute: typeof AppMisTareasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cuenta': {
      id: '/_app/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AppCuentaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/centro-de-asignaciones': {
      id: '/_app/centro-de-asignaciones'
      path: '/centro-de-asignaciones'
      fullPath: '/centro-de-asignaciones'
      preLoaderRoute: typeof AppCentroDeAsignacionesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tareas': {
      id: '/_app/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof AppTareasRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/usuarios/': {
      id: '/_app/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tableros/': {
      id: '/_app/tableros/'
      path: '/tableros'
      fullPath: '/tableros'
      preLoaderRoute: typeof AppTablerosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/usuarios/$userSlug': {
      id: '/_app/usuarios/$userSlug'
      path: '/usuarios/$userSlug'
      fullPath: '/usuarios/$userSlug'
      preLoaderRoute: typeof AppUsuariosUserSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tableros/$tablero': {
      id: '/_app/tableros/$tablero'
      path: '/tableros/$tablero'
      fullPath: '/tableros/$tablero'
      preLoaderRoute: typeof AppTablerosTableroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tareas/nueva/': {
      id: '/_app/tareas/nueva/'
      path: '/nueva'
      fullPath: '/tareas/nueva'
      preLoaderRoute: typeof AppTareasNuevaIndexRouteImport
      parentRoute: typeof AppTareasRouteRoute
    }
    '/_app/tareas/nueva/impresa': {
      id: '/_app/tareas/nueva/impresa'
      path: '/nueva/impresa'
      fullPath: '/tareas/nueva/impresa'
      preLoaderRoute: typeof AppTareasNuevaImpresaRouteImport
      parentRoute: typeof AppTareasRouteRoute
    }
    '/_app/tareas/nueva/especial': {
      id: '/_app/tareas/nueva/especial'
      path: '/nueva/especial'
      fullPath: '/tareas/nueva/especial'
      preLoaderRoute: typeof AppTareasNuevaEspecialRouteImport
      parentRoute: typeof AppTareasRouteRoute
    }
    '/_app/tareas/nueva/ecommerce': {
      id: '/_app/tareas/nueva/ecommerce'
      path: '/nueva/ecommerce'
      fullPath: '/tareas/nueva/ecommerce'
      preLoaderRoute: typeof AppTareasNuevaEcommerceRouteImport
      parentRoute: typeof AppTareasRouteRoute
    }
    '/_app/tareas/nueva/digital': {
      id: '/_app/tareas/nueva/digital'
      path: '/nueva/digital'
      fullPath: '/tareas/nueva/digital'
      preLoaderRoute: typeof AppTareasNuevaDigitalRouteImport
      parentRoute: typeof AppTareasRouteRoute
    }
  }
}

interface AppTareasRouteRouteChildren {
  AppTareasNuevaDigitalRoute: typeof AppTareasNuevaDigitalRoute
  AppTareasNuevaEcommerceRoute: typeof AppTareasNuevaEcommerceRoute
  AppTareasNuevaEspecialRoute: typeof AppTareasNuevaEspecialRoute
  AppTareasNuevaImpresaRoute: typeof AppTareasNuevaImpresaRoute
  AppTareasNuevaIndexRoute: typeof AppTareasNuevaIndexRoute
}

const AppTareasRouteRouteChildren: AppTareasRouteRouteChildren = {
  AppTareasNuevaDigitalRoute: AppTareasNuevaDigitalRoute,
  AppTareasNuevaEcommerceRoute: AppTareasNuevaEcommerceRoute,
  AppTareasNuevaEspecialRoute: AppTareasNuevaEspecialRoute,
  AppTareasNuevaImpresaRoute: AppTareasNuevaImpresaRoute,
  AppTareasNuevaIndexRoute: AppTareasNuevaIndexRoute,
}

const AppTareasRouteRouteWithChildren = AppTareasRouteRoute._addFileChildren(
  AppTareasRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppTareasRouteRoute: typeof AppTareasRouteRouteWithChildren
  AppAjustesRoute: typeof AppAjustesRoute
  AppCentroDeAsignacionesRoute: typeof AppCentroDeAsignacionesRoute
  AppCuentaRoute: typeof AppCuentaRoute
  AppMisTareasRoute: typeof AppMisTareasRoute
  AppSolicitudesRoute: typeof AppSolicitudesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTablerosTableroRoute: typeof AppTablerosTableroRoute
  AppUsuariosUserSlugRoute: typeof AppUsuariosUserSlugRoute
  AppTablerosIndexRoute: typeof AppTablerosIndexRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTareasRouteRoute: AppTareasRouteRouteWithChildren,
  AppAjustesRoute: AppAjustesRoute,
  AppCentroDeAsignacionesRoute: AppCentroDeAsignacionesRoute,
  AppCuentaRoute: AppCuentaRoute,
  AppMisTareasRoute: AppMisTareasRoute,
  AppSolicitudesRoute: AppSolicitudesRoute,
  AppIndexRoute: AppIndexRoute,
  AppTablerosTableroRoute: AppTablerosTableroRoute,
  AppUsuariosUserSlugRoute: AppUsuariosUserSlugRoute,
  AppTablerosIndexRoute: AppTablerosIndexRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
